import type { Category } from '@ut/types'

export interface LocationData {
  title: string
  slug: string
  district: string
  category: Category
  coordinates: { lat: number; lng: number }
  bestSeason: string
  accessibility: string
  description: string
  travelTips: string[]
  nearbyAttractions: string[]
  osmLink: string
}

export const LOCATIONS: LocationData[] = [
  {
    title: 'Kuntala Waterfalls',
    slug: 'kuntala-waterfalls',
    district: 'adilabad',
    category: 'waterfalls',
    coordinates: { lat: 19.289, lng: 78.5 },
    bestSeason: 'August – December',
    accessibility: 'Steps descent to the base; moderate difficulty',
    description:
      'The highest waterfall in Telangana at 45 meters, cascading down rocky cliffs within the dense Sahyadri forests. A sight of pure force in monsoon.',
    travelTips: [
      'Wear sturdy shoes for the descent',
      'Visit early morning to avoid crowds',
      'Pack a picnic — there are scenic spots at the base',
    ],
    nearbyAttractions: ['Pochera Falls', 'Kawal Wildlife Sanctuary', 'Nagoba Temple'],
    osmLink: 'https://www.openstreetmap.org/node/4694725366',
  },
  {
    title: 'Bogatha Waterfall',
    slug: 'bogatha-waterfall',
    district: 'mulugu',
    category: 'waterfalls',
    coordinates: { lat: 18.261, lng: 80.316 },
    bestSeason: 'August – November',
    accessibility: 'Road access with short walk from parking',
    description:
      'Often called the Niagara of Telangana, this multi-tier waterfall on the Kadem river plunges dramatically over a wide horseshoe cliff face.',
    travelTips: [
      'Combine with a visit to Ramappa Temple',
      'Carry rain protection in monsoon',
      'Local stalls sell bamboo chicken',
    ],
    nearbyAttractions: ['Ramappa Temple', 'Laknavaram Lake', 'Medaram Temple'],
    osmLink: 'https://www.openstreetmap.org/node/4694725370',
  },
  {
    title: 'Pochera Waterfalls',
    slug: 'pochera-waterfalls',
    district: 'adilabad',
    category: 'waterfalls',
    coordinates: { lat: 19.195, lng: 78.324 },
    bestSeason: 'August – January',
    accessibility: 'Short trek from parking area; slippery in monsoon',
    description:
      'A hidden cascade tucked into a deep gorge of the Sahyadri range, Pochera is famous for its thunderous roar and cool spray zone during peak monsoon.',
    travelTips: [
      'Avoid swimming — currents are strong',
      'Best photographed from the viewing platform',
      'Combine with Kuntala Falls (30 min drive)',
    ],
    nearbyAttractions: ['Kuntala Falls', 'Kawal Wildlife Sanctuary', 'Basar Saraswati Temple'],
    osmLink: 'https://www.openstreetmap.org/node/4694725375',
  },
  {
    title: 'Ramappa Temple',
    slug: 'ramappa-temple',
    district: 'mulugu',
    category: 'temples',
    coordinates: { lat: 18.258, lng: 79.943 },
    bestSeason: 'October – February',
    accessibility: 'Paved road; wheelchair ramps at entrance',
    description:
      "13th-century Kakatiya masterpiece and Telangana's first UNESCO World Heritage Site. Famous for floating bricks, exquisite bracket figures, and the monolithic Nandi.",
    travelTips: [
      'Hire the official guide for the full story',
      'Visit on weekdays to avoid crowds',
      "Don't miss the floating brick demo",
    ],
    nearbyAttractions: ['Laknavaram Lake', 'Bogatha Waterfall', 'Medaram Temple'],
    osmLink: 'https://www.openstreetmap.org/way/648258921',
  },
  {
    title: 'Thousand Pillar Temple',
    slug: 'thousand-pillar-temple',
    district: 'warangal',
    category: 'temples',
    coordinates: { lat: 18.003, lng: 79.574 },
    bestSeason: 'October – March',
    accessibility: 'In Hanamkonda town center; level walk from parking',
    description:
      'Built in 1163 CE, this star-shaped triple shrine dedicated to Shiva, Vishnu, and Surya features hundreds of intricately carved pillars, each unique in design.',
    travelTips: [
      'Photography allowed in outer areas only',
      'Combine with Warangal Fort and Bhadrakali Temple',
      'Evening light is magical for photos',
    ],
    nearbyAttractions: ['Warangal Fort', 'Bhadrakali Temple', 'Kakatiya Rock Garden'],
    osmLink: 'https://www.openstreetmap.org/way/154316711',
  },
  {
    title: 'Warangal Fort',
    slug: 'warangal-fort',
    district: 'warangal',
    category: 'forts',
    coordinates: { lat: 17.959, lng: 79.608 },
    bestSeason: 'October – March',
    accessibility: 'Large open site with paved pathways',
    description:
      'The 13th-century Kakatiya citadel spanning 19 km — its iconic Kala Thoranam gateways are the emblem of Telangana. The sprawling ruins reveal temples, ceremonial halls, and the legendary Svayambhu Lingam.',
    travelTips: [
      'Carry water and a hat — little shade across the site',
      'Start at the Swyambhu temple and walk toward the gateways',
      'Sunset light on the stone archways is stunning',
    ],
    nearbyAttractions: ['Thousand Pillar Temple', 'Bhadrakali Temple', 'Kakatiya Musical Garden'],
    osmLink: 'https://www.openstreetmap.org/relation/2025827',
  },
  {
    title: 'Golconda Fort',
    slug: 'golconda-fort',
    district: 'hyderabad',
    category: 'forts',
    coordinates: { lat: 17.3833, lng: 78.4011 },
    bestSeason: 'October – February',
    accessibility: 'Steep climb to the top; moderate difficulty',
    description:
      'The legendary diamond capital of the world, Golconda Fort spans 11 km of fortified walls. The acoustics are still legendary — a clap at the Fateh Darwaza echoes a kilometer away at the Bala Hissar pavilion.',
    travelTips: [
      'Book the evening sound and light show',
      'Wear comfortable walking shoes',
      'Hire an ASI guide for the hidden escape tunnels story',
    ],
    nearbyAttractions: ['Qutb Shahi Tombs', 'Taramati Baradari', 'Hussain Sagar'],
    osmLink: 'https://www.openstreetmap.org/way/30805650',
  },
  {
    title: 'Charminar',
    slug: 'charminar',
    district: 'hyderabad',
    category: 'hidden-gems',
    coordinates: { lat: 17.3616, lng: 78.4747 },
    bestSeason: 'Year-round (avoid summer afternoons)',
    accessibility: 'In Old City; narrow crowded streets; motorable to the base',
    description:
      'The iconic 1591 monument with four minarets, built by Mohammed Quli Qutb Shah. The surrounding Laad Bazaar is a labyrinth of pearl shops, attar perfume stalls, and Irani chai cafés.',
    travelTips: [
      'Climb the minaret for panoramic Old City views',
      'Explore Laad Bazaar for pearls and bangles',
      'Try Irani chai at Nimrah Cafe across the road',
    ],
    nearbyAttractions: ['Chowmahalla Palace', 'Mecca Masjid', 'Salar Jung Museum'],
    osmLink: 'https://www.openstreetmap.org/way/154316712',
  },
  {
    title: 'Yadadri Lakshmi Narasimha Swamy Temple',
    slug: 'yadadri-temple',
    district: 'yadadri-bhuvanagiri',
    category: 'temples',
    coordinates: { lat: 17.484, lng: 78.866 },
    bestSeason: 'October – March',
    accessibility: 'Hilltop temple with steps and road access; elevator for elderly',
    description:
      'A massive temple complex recently renovated with exquisite Kakatiya-style stone architecture. Dedicated to Lord Narasimha, it sits atop a scenic hill drawing millions of devotees annually.',
    travelTips: [
      'Visit on weekdays to avoid huge queues',
      'Free meals served at the temple canteen',
      'Bhongir Fort is just 30 min away',
    ],
    nearbyAttractions: [
      'Bhongir Fort',
      'Surendrapuri Mythological Museum',
      'Kolanupaka Jain Temple',
    ],
    osmLink: 'https://www.openstreetmap.org/way/555433033',
  },
  {
    title: 'Bhongir Fort',
    slug: 'bhongir-fort',
    district: 'yadadri-bhuvanagiri',
    category: 'forts',
    coordinates: { lat: 17.516, lng: 78.888 },
    bestSeason: 'October – February',
    accessibility: 'Steep rock climb; challenging for elderly',
    description:
      'An imposing monolith fort built by the Chalukya ruler Tribhuvanamalla Vikramaditya in the 10th century. The 500-foot egg-shaped rock fortress offers a physically demanding but rewarding climb with panoramic views.',
    travelTips: [
      'Start early morning to beat the heat',
      'No food/water at the top — pack your own',
      'Paragliding available during season',
    ],
    nearbyAttractions: ['Yadadri Temple', 'Kolanupaka Jain Temple', 'Surendrapuri Museum'],
    osmLink: 'https://www.openstreetmap.org/way/41103572',
  },
  {
    title: 'Nagarjuna Sagar Dam',
    slug: 'nagarjuna-sagar-dam',
    district: 'nalgonda',
    category: 'reservoirs',
    coordinates: { lat: 16.577, lng: 79.314 },
    bestSeason: 'October – March',
    accessibility: 'Well-paved road; viewpoints along the dam wall',
    description:
      "One of the world's largest masonry dams built across the Krishna River, creating a vast reservoir. The adjacent Nagarjunakonda island museum houses remarkable Buddhist relics relocated before the valley was submerged.",
    travelTips: [
      'Take the boat to Nagarjunakonda island (3 hrs round trip)',
      'Visit the museum first for context',
      'Gates open only during flood season',
    ],
    nearbyAttractions: [
      'Nagarjunakonda Museum',
      'Ethipothala Falls',
      'Macherla Lakshmi Narasimha Temple',
    ],
    osmLink: 'https://www.openstreetmap.org/way/28861563',
  },
  {
    title: 'Basar Saraswati Temple',
    slug: 'basar-saraswati-temple',
    district: 'nirmal',
    category: 'temples',
    coordinates: { lat: 18.877, lng: 77.949 },
    bestSeason: 'October – February (Vasant Panchami is peak)',
    accessibility: 'Well-connected by road; near Basar railway station on Godavari banks',
    description:
      'One of the only two Saraswati temples in India, this ancient shrine on the Godavari river bank is where parents bring children for Aksharabhyasam — the ritual of initiating a child into writing.',
    travelTips: [
      'Book the Aksharabhyasam ceremony slot in advance',
      'Visit during Vasant Panchami for the grand celebration',
      'Take a holy dip in the Godavari',
    ],
    nearbyAttractions: ['Nirmal Fort', 'Kadam Dam', 'Nirmal Toys & Crafts village'],
    osmLink: 'https://www.openstreetmap.org/node/2453768142',
  },
  {
    title: 'Khammam Fort',
    slug: 'khammam-fort',
    district: 'khammam',
    category: 'forts',
    coordinates: { lat: 17.242, lng: 80.146 },
    bestSeason: 'October – March',
    accessibility: 'In Khammam town center; moderate climb',
    description:
      'A 10th-century hilltop fort built by the Kakatiyas and later expanded by the Qutb Shahis, offering commanding views of the entire Khammam town. The blend of Kakatiya and Islamic architecture is distinctive.',
    travelTips: [
      'Early mornings have the best light for photos',
      'Combine with a visit to Lakaram Lake',
      'Local street food around the fort is excellent',
    ],
    nearbyAttractions: ['Lakaram Lake', 'Narasimhaswamy Temple', 'Kinnerasani Wildlife Sanctuary'],
    osmLink: 'https://www.openstreetmap.org/way/446917297',
  },
  {
    title: 'Medak Cathedral',
    slug: 'medak-cathedral',
    district: 'medak',
    category: 'hidden-gems',
    coordinates: { lat: 18.044, lng: 78.26 },
    bestSeason: 'Year-round (especially Christmas week)',
    accessibility: 'Ground level access; wheelchair friendly',
    description:
      'One of the largest churches in Asia, this stunning Gothic Revival cathedral built by British Wesleyan Methodists features intricate stained glass windows crafted in Italy and a bell tower visible for miles.',
    travelTips: [
      'Visit during Sunday service for the full experience',
      'The stained glass is best seen in morning light',
      'Medak Fort is 10 min away',
    ],
    nearbyAttractions: ['Medak Fort', 'Pocharam Wildlife Sanctuary', 'Pocharam Dam'],
    osmLink: 'https://www.openstreetmap.org/way/110537620',
  },
  {
    title: 'Koilkonda Fort',
    slug: 'koilkonda-fort',
    district: 'mahabubnagar',
    category: 'forts',
    coordinates: { lat: 16.592, lng: 78.171 },
    bestSeason: 'October – February',
    accessibility: 'Hilltop fort with a steep climb; about 500 steps',
    description:
      'Perched on a hilltop at 1,200 feet, this 14th-century Qutb Shahi fort has seven tiers of fortifications rising dramatically from the plains. The panoramic views stretch for miles across the Deccan.',
    travelTips: [
      'Carry 2L of water — no shops at the top',
      'Start before 7 AM in summer',
      'Club with Pillalamarri Banyan Tree (1 hr drive)',
    ],
    nearbyAttractions: ['Pillalamarri Banyan Tree', 'Jurala Dam', 'Beechupally Anjaneya Temple'],
    osmLink: 'https://www.openstreetmap.org/node/2453768148',
  },
  {
    title: 'Pocharam Wildlife Sanctuary',
    slug: 'pocharam-sanctuary',
    district: 'medak',
    category: 'wildlife',
    coordinates: { lat: 18.194, lng: 78.148 },
    bestSeason: 'November – March',
    accessibility: 'Forest roads; 4x4 recommended in monsoon',
    description:
      'A 130 sq km haven for spotted deer, blackbuck, wild boar, and migratory birds. The sanctuary wraps around the Pocharam reservoir, creating a mosaic of wetland and dry deciduous forest habitats.',
    travelTips: [
      'Book the forest department safari in advance',
      'Binoculars essential for birdwatching',
      'No food stalls inside — carry snacks',
    ],
    nearbyAttractions: ['Medak Cathedral', 'Pocharam Dam', 'Medak Fort'],
    osmLink: 'https://www.openstreetmap.org/relation/3305917',
  },
  {
    title: 'Sriram Sagar Dam (Pochampadu)',
    slug: 'sriram-sagar-dam',
    district: 'nizamabad',
    category: 'reservoirs',
    coordinates: { lat: 18.968, lng: 78.273 },
    bestSeason: 'October – March',
    accessibility: 'Well-paved road to the dam site',
    description:
      "A lifeline of Telangana's agriculture built across the Godavari, this massive earth dam and its scenic reservoir is a popular picnic spot. Boating and sunset viewpoints draw visitors year-round.",
    travelTips: [
      'Sunset from the dam wall is spectacular',
      'Boating available on weekends',
      'Pack your own food — limited stalls',
    ],
    nearbyAttractions: ['Nizamabad Fort', 'Alisagar Reservoir', 'Dichpally Ramalayam'],
    osmLink: 'https://www.openstreetmap.org/way/35384500',
  },
  {
    title: 'Eturnagaram Wildlife Sanctuary',
    slug: 'eturnagaram-sanctuary',
    district: 'mulugu',
    category: 'wildlife',
    coordinates: { lat: 18.305, lng: 80.225 },
    bestSeason: 'November – March',
    accessibility: 'Forested tracks; guided safaris only',
    description:
      "One of Telangana's oldest sanctuaries, Eturnagaram sits at the trijunction of Godavari and its tributaries. Leopards, sloth bears, sambar, and over 160 bird species inhabit this dense teak forest.",
    travelTips: [
      'Book the forest safari 2 days ahead',
      'Stay at the forest guest house for the full experience',
      'Carry mosquito repellent',
    ],
    nearbyAttractions: ['Laknavaram Lake', 'Ramappa Temple', 'Medaram Temple'],
    osmLink: 'https://www.openstreetmap.org/relation/3305925',
  },
  {
    title: 'Hussain Sagar Lake',
    slug: 'hussain-sagar-lake',
    district: 'hyderabad',
    category: 'lakes',
    coordinates: { lat: 17.4239, lng: 78.4738 },
    bestSeason: 'Year-round (evenings are best)',
    accessibility: 'Fully urban; multiple entry points; boating from Lumbini Park',
    description:
      'The heart-shaped lake built by Ibrahim Quli Qutb Shah in 1563, connecting Hyderabad and Secunderabad. The giant monolithic Buddha statue at its center is a city icon. The Necklace Road promenade encircles it.',
    travelTips: [
      'Boat ride to the Buddha statue from Lumbini Park',
      'Evening walk along Necklace Road',
      'Visit Sanjeevaiah Park for birdwatching',
    ],
    nearbyAttractions: ['Lumbini Park', 'Birla Mandir', 'Snow World'],
    osmLink: 'https://www.openstreetmap.org/relation/6341605',
  },
  {
    title: 'Laknavaram Lake',
    slug: 'laknavaram-lake',
    district: 'mulugu',
    category: 'lakes',
    coordinates: { lat: 18.157, lng: 80.041 },
    bestSeason: 'October – March',
    accessibility: 'Well-paved road; suspension bridge to the island',
    description:
      'A stunning 10,000-acre lake with dozens of small islands connected by a charming suspension bridge. Telangana Tourism runs cottages and camping on the main island — truly unforgettable.',
    travelTips: [
      'Book the island cottages at least 2 weeks ahead',
      'Boating and kayaking available',
      'The suspension bridge at golden hour is pure magic',
    ],
    nearbyAttractions: ['Ramappa Temple', 'Bogatha Waterfall', 'Eturnagaram Sanctuary'],
    osmLink: 'https://www.openstreetmap.org/relation/6341606',
  },
  {
    title: 'Pakhal Lake',
    slug: 'pakhal-lake',
    district: 'warangal',
    category: 'lakes',
    coordinates: { lat: 17.953, lng: 79.997 },
    bestSeason: 'October – March',
    accessibility: 'Road access; last 2 km rough',
    description:
      'Built in 1213 CE by Kakatiya king Ganapati Deva, this serene lake is surrounded by the Pakhal Wildlife Sanctuary. The lake is 30 sq km and framed by dense forests — ideal for quiet birdwatching.',
    travelTips: [
      'Visit at sunrise for spectacular bird activity',
      'Carry a bird guide — 100+ species recorded',
      'Combine with a visit to the sanctuary',
    ],
    nearbyAttractions: ['Pakhal Wildlife Sanctuary', 'Ramappa Temple', 'Eturnagaram Sanctuary'],
    osmLink: 'https://www.openstreetmap.org/relation/6341607',
  },
  {
    title: 'Nirmal Paintings & Toys Village',
    slug: 'nirmal-crafts',
    district: 'nirmal',
    category: 'hidden-gems',
    coordinates: { lat: 19.096, lng: 78.344 },
    bestSeason: 'Year-round',
    accessibility: 'In Nirmal town; shops and workshops walkable from the bus stand',
    description:
      "Nirmal is synonymous with the 400-year-old Nirmal paintings — intricate gold-embellished art on lacquered Ponniki wood — and exquisitely carved wooden toys. The town's artisan cluster is a living heritage.",
    travelTips: [
      'Visit the government-run Lepakshi emporium for guaranteed authentic pieces',
      'Many workshops welcome visitors to watch the craft',
      'Nirmal Fort ruins are nearby',
    ],
    nearbyAttractions: ['Basar Saraswati Temple', 'Kadam Dam', 'Adelli Pochamma Temple'],
    osmLink: 'https://www.openstreetmap.org/node/2453768150',
  },
  {
    title: 'Chowmahalla Palace',
    slug: 'chowmahalla-palace',
    district: 'hyderabad',
    category: 'museums',
    coordinates: { lat: 17.3577, lng: 78.4715 },
    bestSeason: 'Year-round',
    accessibility: 'Fully accessible; in Old City near Charminar',
    description:
      'The seat of the Nizams of Hyderabad — four palaces around a grand courtyard with the Durbar Hall featuring 19 Belgian crystal chandeliers. The vintage Rolls Royce collection is extraordinary.',
    travelTips: [
      'Buy a combined ticket with Charminar',
      'Allow 2 hours minimum',
      'The Durbar Hall photography is breathtaking',
    ],
    nearbyAttractions: ['Charminar', 'Mecca Masjid', 'Laad Bazaar'],
    osmLink: 'https://www.openstreetmap.org/way/154316713',
  },
  {
    title: 'Salar Jung Museum',
    slug: 'salar-jung-museum',
    district: 'hyderabad',
    category: 'museums',
    coordinates: { lat: 17.3714, lng: 78.4803 },
    bestSeason: 'Year-round',
    accessibility: 'Fully accessible; elevator and ramps available',
    description:
      "One of India's three National Museums, housing the personal collection of the Salar Jung family — 43,000 art objects, 50,000 books, and the famous Veiled Rebecca marble statue.",
    travelTips: [
      'Plan at least 3 hours — the collection is enormous',
      'The audio guide greatly enhances the experience',
      'Closed on Fridays',
    ],
    nearbyAttractions: ['Charminar', 'Chowmahalla Palace', 'Nizam Museum'],
    osmLink: 'https://www.openstreetmap.org/way/154316714',
  },
  {
    title: 'Ananthagiri Hills',
    slug: 'ananthagiri-hills',
    district: 'vikarabad',
    category: 'viewpoints',
    coordinates: { lat: 17.316, lng: 77.863 },
    bestSeason: 'October – March',
    accessibility: 'Paved road to the top; short walks to viewpoints',
    description:
      'The birthplace of the Musi River, Ananthagiri Hills is a forested retreat just 80 km from Hyderabad. Coffee plantations, ancient temples, misty mornings, and panoramic valley views make it a weekend favorite.',
    travelTips: [
      'Start early — sunsets from the viewpoints are legendary',
      'Visit the Anantha Padmanabha Swamy Temple',
      'Trek to the Musi origin point',
    ],
    nearbyAttractions: [
      'Kotipally Reservoir',
      'Bugga Rameswaram Temple',
      'Vikarabad Forest trek trails',
    ],
    osmLink: 'https://www.openstreetmap.org/node/2453768155',
  },
  {
    title: 'Pillalamarri Banyan Tree',
    slug: 'pillalamarri-banyan-tree',
    district: 'mahabubnagar',
    category: 'eco-tourism',
    coordinates: { lat: 16.722, lng: 78.036 },
    bestSeason: 'October – March',
    accessibility: 'Level walk from parking; well-maintained pathway',
    description:
      'A colossal 700-year-old banyan tree spread over 4 acres, with thousands of aerial roots creating a natural canopy labyrinth. Located next to a tranquil 12th-century Kakatiya temple.',
    travelTips: [
      'Now protected — walking on roots is prohibited',
      'Bring a wide-angle lens for photography',
      'Accessible as a day trip from Hyderabad',
    ],
    nearbyAttractions: ['Koilkonda Fort', 'Jurala Dam', 'Uma Maheshwaram Temple'],
    osmLink: 'https://www.openstreetmap.org/node/2453768160',
  },
  {
    title: 'Mid Manair Dam',
    slug: 'mid-manair-dam',
    district: 'rajanna-sircilla',
    category: 'reservoirs',
    coordinates: { lat: 18.336, lng: 78.711 },
    bestSeason: 'October – March',
    accessibility: 'Drive-up access; paved road',
    description:
      "A major irrigation dam on the Manair River with a scenic reservoir popular for picnics, fishing, and sunset views. The engineering scale and the surrounding green hills make it a photographer's delight.",
    travelTips: [
      'Great sunset photography spot',
      'Fishing permitted with local permits',
      'Carry your own supplies — few shops nearby',
    ],
    nearbyAttractions: ['Vemulawada Temple', 'Kondagattu Anjaneya Temple', 'Dharmapuri Temple'],
    osmLink: 'https://www.openstreetmap.org/way/28861564',
  },
  {
    title: 'Phanigiri Buddhist Site',
    slug: 'phanigiri-buddhist-site',
    district: 'suryapet',
    category: 'archaeological',
    coordinates: { lat: 17.063, lng: 79.541 },
    bestSeason: 'October – March',
    accessibility: 'Hilltop site with moderate climb from parking',
    description:
      'A 2nd-century BCE Buddhist monastery complex recently excavated — stupas, viharas, chaitya halls, and intricate carvings reveal a major center of Hinayana and Mahayana Buddhism on the Krishna river trade route.',
    travelTips: [
      'Carry water and a hat — exposed site with little shade',
      'The ASI information boards are excellent',
      'Combine with Nagarjuna Sagar trip',
    ],
    nearbyAttractions: ['Nagarjuna Sagar Dam', 'Ethipothala Falls', 'Nagarjunakonda Museum'],
    osmLink: 'https://www.openstreetmap.org/node/2453768165',
  },
  {
    title: 'Jurala Dam',
    slug: 'jurala-dam',
    district: 'jogulamba-gadwal',
    category: 'reservoirs',
    coordinates: { lat: 16.34, lng: 77.792 },
    bestSeason: 'August – February',
    accessibility: 'Paved road to the dam; viewpoints along the wall',
    description:
      'Built across the Krishna River, the Jurala Dam creates a vast and scenic reservoir. The massive gates releasing water during monsoon are an awe-inspiring sight. Crocodile sightings are common in the backwaters.',
    travelTips: [
      'Visit in monsoon to see the gates open',
      'Boating available on weekends',
      'Crocodile spotting from a safe distance',
    ],
    nearbyAttractions: ['Gadwal Fort', 'Jogulamba Temple', 'Beechupally Anjaneya Temple'],
    osmLink: 'https://www.openstreetmap.org/way/35384501',
  },
  {
    title: 'Bhadrakali Temple',
    slug: 'bhadrakali-temple',
    district: 'warangal',
    category: 'temples',
    coordinates: { lat: 17.994, lng: 79.58 },
    bestSeason: 'Year-round (Navaratri is spectacular)',
    accessibility: 'On Bhadrakali Bund; level walk from parking',
    description:
      "One of Telangana's oldest temples, this 625 CE shrine houses a 2.7-meter fierce stone idol of the goddess Bhadrakali. Set on a scenic lakefront, the temple is deeply sacred for the Kakatiya legacy.",
    travelTips: [
      'Visit during early morning aarti',
      'The lake views from the temple steps are serene',
      'Navaratri celebrations here are among the largest in Telangana',
    ],
    nearbyAttractions: ['Thousand Pillar Temple', 'Warangal Fort', 'Kakatiya Musical Garden'],
    osmLink: 'https://www.openstreetmap.org/way/154316715',
  },
  {
    title: 'Jogulamba Temple',
    slug: 'jogulamba-temple',
    district: 'jogulamba-gadwal',
    category: 'temples',
    coordinates: { lat: 16.233, lng: 77.796 },
    bestSeason: 'October – March',
    accessibility: 'In Alampur town; level access',
    description:
      'One of the 18 Shakti Peethas in India, the Jogulamba temple at Alampur is a sacred Shakti shrine on the Tungabhadra bank. The adjacent Nava Brahma temples showcase exquisite Badami Chalukya architecture from the 7th century.',
    travelTips: [
      'Visit all 9 Nava Brahma temples in a single circuit',
      'The ASI museum nearby has excellent sculpture displays',
      'Alampur is a no-alcohol, no-meat pilgrimage town',
    ],
    nearbyAttractions: ['Nava Brahma Temples', 'Sangameswara Temple', 'Alampur ASI Museum'],
    osmLink: 'https://www.openstreetmap.org/way/35384502',
  },
  {
    title: 'Kolanupaka Jain Temple',
    slug: 'kolanupaka-jain-temple',
    district: 'yadadri-bhuvanagiri',
    category: 'temples',
    coordinates: { lat: 17.702, lng: 79.052 },
    bestSeason: 'October – March',
    accessibility: 'Level walk from parking; wheelchair accessible',
    description:
      'A 2000-year-old Jain temple housing a magnificent 1.5-meter jade statue of Lord Mahavira. The intricate Kakatiya-style architecture and serene atmosphere make it a profound spiritual and architectural site.',
    travelTips: [
      'All visitors must cover legs; sarongs provided',
      'Photography inside the sanctum is restricted',
      'The temple museum explains Jain iconography',
    ],
    nearbyAttractions: ['Yadadri Temple', 'Bhongir Fort', 'Surendrapuri Museum'],
    osmLink: 'https://www.openstreetmap.org/way/35384503',
  },
  {
    title: 'Pandavula Gutta',
    slug: 'pandavula-gutta',
    district: 'jayashankar-bhupalpally',
    category: 'archaeological',
    coordinates: { lat: 18.315, lng: 80.002 },
    bestSeason: 'October – March',
    accessibility: 'Moderate trek through forest — guide recommended',
    description:
      "Telangana's premier prehistoric rock art site — cave paintings dating back to the Mesolithic period, over 10,000 years old. Depictions of humans, animals, and geometric patterns in natural red ochre have survived millennia.",
    travelTips: [
      'Hire a local guide — the caves are hard to find',
      'Wear trekking shoes and carry water',
      "Do not touch the paintings — they're fragile",
    ],
    nearbyAttractions: ['Laknavaram Lake', 'Ramappa Temple', 'Eturnagaram Sanctuary'],
    osmLink: 'https://www.openstreetmap.org/node/2453768170',
  },
  {
    title: 'Kondagattu Anjaneya Temple',
    slug: 'kondagattu-temple',
    district: 'jagtial',
    category: 'temples',
    coordinates: { lat: 18.756, lng: 78.889 },
    bestSeason: 'October – March',
    accessibility: 'Hilltop temple with road access and steps',
    description:
      "A hilltop Hanuman temple surrounded by dense forests, believed to be self-manifested. The scenic drive through the hills and the temple's peaceful atmosphere attract devotees from across the region.",
    travelTips: [
      'Saturdays are extremely crowded — weekdays are better',
      'The forest views from the hilltop are stunning',
      'Free meals served at the temple',
    ],
    nearbyAttractions: ['Vemulawada Temple', 'Dharmapuri Temple', 'Mid Manair Dam'],
    osmLink: 'https://www.openstreetmap.org/node/2453768175',
  },
  {
    title: 'Elgandal Fort',
    slug: 'elgandal-fort',
    district: 'karimnagar',
    category: 'forts',
    coordinates: { lat: 18.456, lng: 79.067 },
    bestSeason: 'October – March',
    accessibility: 'Hilltop fort; steep climb on foot',
    description:
      'A millennium-old fort on the banks of the Manair River, occupied successively by the Kakatiyas, Qutb Shahis, and Asaf Jahis. The blend of architectural styles across centuries tells the layered history of the Deccan.',
    travelTips: [
      'Visit at sunrise or sunset for the best light',
      'The mosque and stepwell inside the fort are highlights',
      'Carry water — no facilities at the top',
    ],
    nearbyAttractions: ['Lower Manair Dam', 'Karimnagar Deer Park', 'Rajiv Gandhi Deer Park'],
    osmLink: 'https://www.openstreetmap.org/way/35384504',
  },
  {
    title: 'Lower Manair Dam',
    slug: 'lower-manair-dam',
    district: 'karimnagar',
    category: 'reservoirs',
    coordinates: { lat: 18.392, lng: 79.134 },
    bestSeason: 'October – March',
    accessibility: 'Drive-up access with parking area',
    description:
      "A scenic dam on the Manair River, surrounded by manicured gardens and a children's park. Popular with families for weekend outings, boating, and sunset watching.",
    travelTips: [
      'Boating available on weekends',
      'The gardens are well-maintained — great for families',
      'Visit the deer park nearby',
    ],
    nearbyAttractions: ['Elgandal Fort', 'Karimnagar Deer Park', 'Rajiv Gandhi Deer Park'],
    osmLink: 'https://www.openstreetmap.org/way/35384505',
  },
  {
    title: 'Kadam Dam',
    slug: 'kadam-dam',
    district: 'nirmal',
    category: 'reservoirs',
    coordinates: { lat: 19.091, lng: 78.462 },
    bestSeason: 'August – February',
    accessibility: 'Paved road; short walk from parking',
    description:
      'A picturesque dam on the Kadam River surrounded by thick teak forests. During and after monsoon, the reservoir brims with water and the lush greenery makes it a stunning photography destination.',
    travelTips: [
      'Visit post-monsoon for the best views',
      "No boating — it's a quiet nature spot",
      'Pack a picnic — no commercial stalls nearby',
    ],
    nearbyAttractions: ['Nirmal Fort', 'Basar Temple', 'Kuntala Falls'],
    osmLink: 'https://www.openstreetmap.org/way/35384506',
  },
  {
    title: 'Wanaparthy Palace',
    slug: 'wanaparthy-palace',
    district: 'wanaparthy',
    category: 'forts',
    coordinates: { lat: 16.361, lng: 78.062 },
    bestSeason: 'October – March',
    accessibility: 'In Wanaparthy town; road access',
    description:
      'The grand 19th-century palace of Raja Rameshwar Rao, the ruler of the Wanaparthy Samsthanam — one of the largest princely estates under the Nizam. The Indo-Saracenic architecture with turrets, arches, and courtyards is breathtaking.',
    travelTips: [
      'The palace now houses a polytechnic college — request permission to enter',
      'The durbar hall and chandeliers are stunning',
      'Combine with a visit to Jurala Dam',
    ],
    nearbyAttractions: ['Jurala Dam', 'Gadwal Fort', 'Jogulamba Temple'],
    osmLink: 'https://www.openstreetmap.org/node/2453768180',
  },
  {
    title: 'Nagarjunakonda Museum',
    slug: 'nagarjunakonda-museum',
    district: 'nalgonda',
    category: 'museums',
    coordinates: { lat: 16.52, lng: 79.234 },
    bestSeason: 'October – March',
    accessibility:
      'Accessible only by boat from the mainland; well-maintained walkways on the island',
    description:
      'An extraordinary island museum containing the Buddhist relics excavated before the valley was submerged by the Nagarjuna Sagar Dam. The reconstructed stupas, statues, and inscriptions span from 3rd century BCE to 4th century CE.',
    travelTips: [
      'Boat service starts at 9:30 AM — plan to arrive early',
      'Allow 3-4 hours including the boat journey',
      'The museum is closed on Fridays',
    ],
    nearbyAttractions: ['Nagarjuna Sagar Dam', 'Ethipothala Falls', 'Anupu Buddhist site'],
    osmLink: 'https://www.openstreetmap.org/node/2453768185',
  },
  {
    title: 'Domakonda Fort',
    slug: 'domakonda-fort',
    district: 'kamareddy',
    category: 'forts',
    coordinates: { lat: 18.27, lng: 78.438 },
    bestSeason: 'October – March',
    accessibility: 'In Domakonda village; level walk from parking',
    description:
      'A 18th-century fortified palace built by the Reddy Rajas, showcasing a beautiful blend of Rajasthani, Mughal, and Deccan architectural styles. The ornate wooden pillars and carved stone balconies are unique.',
    travelTips: [
      'The mahal inside the fort is now a heritage hotel',
      'Visit the nearby Shiva temple inside the fort',
      'Combine with Pocharam Sanctuary',
    ],
    nearbyAttractions: ['Pocharam Sanctuary', 'Medak Cathedral', 'Pocharam Dam'],
    osmLink: 'https://www.openstreetmap.org/node/2453768190',
  },
  {
    title: 'Nizamabad Fort (Quilla Ramalayam)',
    slug: 'nizamabad-fort',
    district: 'nizamabad',
    category: 'forts',
    coordinates: { lat: 18.672, lng: 78.099 },
    bestSeason: 'October – March',
    accessibility: 'In Nizamabad town; short climb from the road',
    description:
      'A commanding hilltop fort built by the Rashtrakutas in the 10th century and later expanded by the Qutb Shahis. The ancient Ramalayam temple within the fort walls and the panoramic views of Nizamabad are remarkable.',
    travelTips: [
      'Visit early morning or late afternoon',
      'The temple inside is active — dress respectfully',
      'Dichpally Ramalayam is 15 min drive',
    ],
    nearbyAttractions: ['Dichpally Ramalayam', 'Alisagar Reservoir', 'Pochampadu Dam'],
    osmLink: 'https://www.openstreetmap.org/way/35384507',
  },
  {
    title: 'Dichpally Ramalayam',
    slug: 'dichpally-ramalayam',
    district: 'nizamabad',
    category: 'temples',
    coordinates: { lat: 18.592, lng: 78.208 },
    bestSeason: 'Year-round (Sri Rama Navami is peak)',
    accessibility: 'Right on the highway; level access from parking',
    description:
      'Often called the Khajuraho of the South, this stunning 14th-century temple built by the Kakatiyas features exquisite erotic sculptures alongside traditional religious iconography on its towering gopuram.',
    travelTips: [
      'Look carefully at the tower — the detailed carvings are extraordinary',
      'Sri Rama Navami festival is grand',
      'The temple has a serene garden courtyard',
    ],
    nearbyAttractions: ['Nizamabad Fort', 'Alisagar Reservoir', 'Basar Temple'],
    osmLink: 'https://www.openstreetmap.org/way/35384508',
  },
  {
    title: 'Ethipothala Falls',
    slug: 'ethipothala-falls',
    district: 'nalgonda',
    category: 'waterfalls',
    coordinates: { lat: 16.653, lng: 79.346 },
    bestSeason: 'August – December',
    accessibility: 'Stairs to the base; moderate climb',
    description:
      'A beautiful 70-foot cascade on the Chandravanka River, a tributary of the Krishna. The waterfall is particularly spectacular after the monsoon. A crocodile breeding center is nearby.',
    travelTips: [
      'Combine with Nagarjuna Sagar Dam trip',
      'The crocodile breeding center is worth a quick visit',
      'Monsoon months are risky — check water conditions',
    ],
    nearbyAttractions: ['Nagarjuna Sagar Dam', 'Nagarjunakonda Museum', 'Phanigiri Buddhist site'],
    osmLink: 'https://www.openstreetmap.org/node/2453768195',
  },
  {
    title: 'Kinnerasani Wildlife Sanctuary',
    slug: 'kinnerasani-sanctuary',
    district: 'bhadradri-kothagudem',
    category: 'wildlife',
    coordinates: { lat: 17.674, lng: 80.693 },
    bestSeason: 'November – March',
    accessibility: 'Forested roads; guided safari recommended',
    description:
      'A scenic 635 sq km sanctuary on the banks of the Kinnerasani River, home to tigers, leopards, gaur, and hundreds of bird species. The Kinnerasani Dam within the sanctuary is a bonus attraction.',
    travelTips: [
      'Book the forest safari through the Telangana Forest Dept website',
      'The dam views are spectacular at sunrise',
      'Best visited December–February for migrating birds',
    ],
    nearbyAttractions: ['Bhadrachalam Temple', 'Parnasala', 'Kinnerasani Dam'],
    osmLink: 'https://www.openstreetmap.org/relation/3305928',
  },
  {
    title: 'Bhadrachalam Temple',
    slug: 'bhadrachalam-temple',
    district: 'bhadradri-kothagudem',
    category: 'temples',
    coordinates: { lat: 17.67, lng: 80.883 },
    bestSeason: 'Year-round (Sri Rama Navami is peak)',
    accessibility: 'On Godavari riverbank; level access',
    description:
      'The sacred Sri Sita Ramachandra Swamy temple on the Godavari banks, built in the 17th century by the saint-composer Kancherla Gopanna (Bhakta Ramadasu). One of the most important Rama temples in South India.',
    travelTips: [
      'Visit during Sri Rama Navami for the celestial wedding ceremony',
      'Boat ride on Godavari from the temple ghat',
      'Parnasala is 35 km — a must-visit',
    ],
    nearbyAttractions: ['Parnasala', 'Kinnerasani Sanctuary', 'Godavari river ghats'],
    osmLink: 'https://www.openstreetmap.org/way/35384509',
  },
] as const
