echo "🏔️  Unexplored Telangana — Content Pipeline"
echo "========================================="
echo ""
echo "To contribute a location, create an MDX file in content/locations/"
echo ""
echo "Template:"
echo "---"
echo "title: \"Location Name\""
echo "slug: \"location-slug\""
echo "district: \"District Name\""
echo "category: \"waterfalls\" # one of: waterfalls, forts, temples, lakes, reservoirs, archaeological, eco-tourism, food, viewpoints, wildlife, camping, museums, hidden-gems"
echo "coordinates:"
echo "  lat: 0.0"
echo "  lng: 0.0"
echo "bestSeason: \"October – March\""
echo "accessibility: \"Description of access\""
echo "travelTips:"
echo "  - \"Tip 1\""
echo "  - \"Tip 2\""
echo "nearbyAttractions:"
echo "  - \"Attraction 1\""
echo "  - \"Attraction 2\""
echo "images:"
echo "  - \"/content/location-slug/01.jpg\""
echo "osmLink: \"https://www.openstreetmap.org/...\""
echo "---"
echo ""
